### ISSUE TITLE
Vault detection

### ISSUE THREAD

**Issue by Magnanix** [koopa516/ParkourFortress-Bugs#10]
Map: pf_Hekto

Location example: First fence right before first door when proceeding normally.

[Normal Route] Bug: Vaulting on normal brush below causes a ledge grab
Alternate Route: Edge brush near the climbable pipe, vaulting there proceeds normally

What should happen: [Normal Route] should vault the fence

What should NOT happen: pf_Kijun, before three ziplines and pipe zigzag, two ledges available to climb. These should not become vault-able.

**Comment by namishere** [comment]
I am considering this fixed as of commit df98c9d. Values may need to be adjusted a little more, but you should find your scenarios working as expected.
