### ISSUE TITLE
Can not start pipe climb when too close to pipe

### ISSUE THREAD

**Issue by JaCoB123456798** [koopa516/ParkourFortress-Bugs#13]
I can't grab the pipe over the gap on pf_airspace_r6 even though the bottom of the pipe is well at my feet.
Edit: Pipes in general are barely functional. I rarely grab onto them.

**Comment by oWave** [comment]
More info: Appears to happen when too close to the pipe, players seems to be climbing the pipe for a moment before getting thrown off, for me either to the left or below the pipe.

[Video](https://streamable.com/athme), I get the climb successfully during the middle part even though I'm I think I'm too close

**Comment by koopa516** [comment]
Fixed in commit b6c531.

Method: Players holding down jump when entering a pipe will no longer automatically dismount the pipe.
