### ISSUE TITLE
[new world] If you jump at the pipe near the end you phase through it.

### ISSUE THREAD

**Issue by octoConnors** [koopa516/ParkourFortress-Bugs#14]
If you hit it running on the ground, you'll climb it normally.

**Comment by koopa516** [comment]
I could not replicate this issue.

**Comment by octoConnors** [comment]
> I could not replicate this issue.

Hit the pipe on New World while in the air. You won't grab it.
If your feet are touching the ground you will.

**Comment by koopa516** [comment]
> Hit the pipe on New World while in the air. You won't grab it.
If your feet are touching the ground you will.

I know, and I have not been able to replicate this, nor have others, so I'm going to consider it fixed
