### ISSUE TITLE
Losing All Speed bug

### ISSUE THREAD

**Issue by jvizzlezz** [koopa516/ParkourFortress-Bugs#19]
When closed beta was out a year or two ago, there was a bug wherein you would be reset to 0 speed after climbing up a ledge, and you would regain speed extremely slowly, essentially crippling you. Lately, the same thing has been happening, though I can't discern why. I think it may have to do with long jumping, as that's where I've seen it happen the most. The first checkpoint on werbad (with the zipline) is awfully prone to this bug, if it helps.

**Comment by koopa516** [comment]
I haven't seen any reports of this, so I'm going to close it. If it's still happening, I will reopen the issue.
