### ISSUE TITLE
Zipline Speed

### ISSUE THREAD

**Issue by jvizzlezz** [koopa516/ParkourFortress-Bugs#21]
This isn't a bug, though I'm not sure how to add "enhancement" to my title. Zipline Speed seems to be way too variable -- when you first get on a zipline, your speed is basically nullified. The longer you stay on it, you become exponentially faster. This can be a problem with long ziplines such as in kijun, as you will eventually go so fast (2000+ hammer units per second) that the game will revert you back to a slower speed to control your movement. In this sense, while I like the idea of gaining speed the longer you're on a zipline for, I believe the range is way too powerful. Having your speed cut drastically when getting on a zipline can hurt the flow of running a map quickly, and then having it ramp up so fast can make it seem a little ridiculous on certain maps where longer ziplines are present.

The suggestion I have is to have a higher minimum speed (upon first getting on the zipline) and to nerf the speed gain over time, which I believe would make ziplines more satisfying.

**Comment by namishere** [comment]
This behavior isn't supposed to happen. While increasing the cap for max zipline scale and tic duration fixes the speed calculations, it doesn't fix the position desync that happens along with this.

**Comment by namishere** [comment]
_Should_ be fixed
