### ISSUE TITLE
Full Speed Upon Respawn

### ISSUE THREAD

**Issue by jvizzlezz** [koopa516/ParkourFortress-Bugs#22]
A part of speedrunning new parkour involves respawning until you achieve max speed and can long jump as soon as you exit the starting zone. This isn't fair to new players, and frankly it's a bit annoying having people die over and over again to do strats that are more or less necessary for getting good times on maps, even if they only save a second or two. I've seen some suggest that you start off with max speed, but I'd much prefer if you started off with 0, as it were in slag parkour.

**Comment by koopa516** [comment]
this is already fixed, but turned off at the moment until I have the chance to re-do the starting zones. But rest assured, normally, one is not able to restart with full speeds

**Comment by namishere** [comment]
Fixed this.. a while back, actually
