### ISSUE TITLE
Potential Death By Falling Bug

### ISSUE THREAD

**Issue by jvizzlezz** [koopa516/ParkourFortress-Bugs#23]
While it's not truly confirmed, I believe that what constitutes for DBF (or dying by falling) seems to change randomly. Sometimes I can fall down a great length and be fine, sometimes I can fall a great length and get stunned, and other times I die as intended. While DBF is a lot more lenient in new parkour than in old, I feel like if there's an inconsistency with how it's handled it could lead to extremely broken runs. As an example, I beat the WR of werbad by getting to the first checkpoint and then just falling all the way down to the ground. Most of the time I die, but a few times I survive and can then just run to the ending as normal, saving a good 5-10 seconds over a normal run. Oftentimes I spam crouch/jump while in the air because I feel as though it makes it more likely to survive, but it still seems extremely random regardless.

**Comment by namishere** [comment]
Part of why the new version feels more lenient is because the check for velocity is done one at the ground, and there's no state of doomed to fall death right now.

**Comment by koopa516** [comment]
Possibly fixed, assigning Nami

**Comment by namishere** [comment]
After attempting to replicate this myself, even double jumping at the last possible moment to reset my velocity, I cannot replicate this, and the velocity I reach is well past dying velocity. I am considering this fixed, if you can still pull this off, please record a demo with the "record" command and send it to me.
