### ISSUE TITLE
Telewallrunning

### ISSUE THREAD

**Issue by jvizzlezz** [koopa516/ParkourFortress-Bugs#25]
In slag parkour, telewallrunning was a staple of speedruns. The better you could TWR, the better your times would be. While TWRing in new parkour has more or less the same range horizontally (ie, a wall on your direct left or direct right) as it did before, the range of teleporting forwards (a wall that is ahead of you, such as the TWR at the beginning of werbad that allows you to get on the pipe much faster) is greatly nerfed. I believe it should be changed back to the way it was, as it enabled many new routes and skips to be opened up that required a lot of skill to do, such as one on factory office, the aforementioned on on werbad (which wasn't hard, but still...) and others. For reference, the factory office TWR is right after you first exit the building and you climb up on the fencing. Standing on top of the fencing, you can TWR forwards to the wall leading to the zipline ahead. Included a picture to illustrate it clearer.
![image](https://user-images.githubusercontent.com/50597170/57652574-ded00200-759d-11e9-8a26-12ab24265a65.png)

The actual HU (hammer unit) difference is about ~240, and, as far as I am aware, that TWR is the farthest one forwards you could go, and even getting that one was extremely difficult.

For less of a bug and more of a suggestion, in old parkour, better/farther TWRs were rewarded with being teleported ahead farther. The tighter to the edge you could make a TWR, the farther ahead you would go. In new parkour, I feel as though you just teleport forwards no matter what. I'm not sure if there's a difference between extreme TWRing and normal WRing, but if there is it isn't very noticeable. If there is no difference, I think there should be, to reward players for performing harder wallruns. If there is a difference, I feel as though it should be more significant. If you're very close to a wall, or downright touching it directly, you shouldn't be teleported forwards even remotely, whereas if you're farther away, you should be teleported forwards by a moderate/noticeable value.

**Comment by koopa516** [comment]
Telewallrunning has been greatly improved due to new tracing methods coded in by Nami, see commit caa7f08.
