### ISSUE TITLE
map vote prompts twice

### ISSUE THREAD

**Issue by flueysucks** [koopa516/ParkourFortress-Bugs#26]
Server cvar 'sm_nextmap' changed to pf_overview_b3
Vote Completed! The next map will be: pf_overview_b3
Warning | Max velocity exceeded.
Server cvar 'sm_nextmap' changed to pf_koosu_s8
Vote Completed! The next map will be: pf_koosu_s8

**Comment by Kenzzer** [comment]
Not a bug, just sourcemod displaying a cvar value that has been changed. This can be resolved by changing our method for updating the cvar.

**Comment by koopa516** [comment]
Fixed in commit 347f3b
