### ISSUE TITLE
Regaining speed by Failing Wallruns

### ISSUE THREAD

**Issue by DaveFlare** [koopa516/ParkourFortress-Bugs#29]
When trying to do a wallrun using the actions to do said wallrun, that being W+A or W+D, even if you fail to do the wallrun, it still gives a speedboost.  By doing three failed wallrun attempts from a stand still, it will bring you to full speed.  When you do the action of trying to wallrun, even if there's no wall to wallrun on, it still commits the action of trying to do a wallrun, and therefore gains the slight speed of that action even by failing to do the action.

**Comment by namishere** [comment]
Fixed in experimental

**Comment by namishere** [comment]
Fix merged to master
