### ISSUE TITLE
certain walls allow for continued wallruns after the wall end / player collision is enabled in wallruns

### ISSUE THREAD

**Issue by itVictor** [koopa516/ParkourFortress-Bugs#3]
(two bugs in one since I have the same demo for both bugs)

first bug can be found by watching the beginning (and then see me testing it with other walls throughout the demo)

second bug can be found starting at tick 4200

http://www.mediafire.com/file/pjnfkn7x5xdx405/wallrun.dem

**Comment by koopa516** [comment]
Wallrun collisions fixed in commit 40ad72.
