### ISSUE TITLE
Getting stuck under things while crouching

### ISSUE THREAD

**Issue by octoConnors** [koopa516/ParkourFortress-Bugs#32]
You're crawling under something and suddenly you're stuck in place, permanently. I was gonna write a map specific bug but I've had this happen several times on different maps in different spots. Got screencaps of a couple of them.
https://imgur.com/NkmxIDE
https://imgur.com/bx3t4Fz
I know for sure this wasn't happening on New World before.

**Comment by koopa516** [comment]
Known issue after the sliding fix, will be addressed soon

**Comment by koopa516** [comment]
Fixed in commit ed189c.

Method: Added a safety trace when the player is forced to unduck. If the trace fails, re-duck the player.
