### ISSUE TITLE
Wall-Climb bugs

### ISSUE THREAD

**Issue by Drand0r** [koopa516/ParkourFortress-Bugs#4]
When attempting to wall-climb most objects/walls OR doing a wall-climb with your crosshair between two objects (on maps like pf_pink and pf_novus), it rejects the climb, however if you attempt this climb repeatedly some strange things can happen:

- You're teleported to the origin point of the map, but the Z-axis is different depending on where you performed the bug.
- If you managed to land on something after performing the bug (usually by building up some speed before doing the bug), your camera and character will shake violently. Trying to land on nearby flat ground using !fly at this point will cause you be constantly teleported to origin point when you land.

Trying to crouch and wall-climb at the same time doing this bug will also cause the super-slowdown bug.

That's the basic concept of this bug, but you'll need to test it out for yourself to understand what the fuck is going on because me and JJ have been messing around with it for hours.

**Comment by koopa516** [comment]
Ah, the classic ROM hack bug. Didn't know this was still open. Fixed ages ago.
