### ISSUE TITLE
Springboards do not work how they use to

### ISSUE THREAD

**Issue by Jvp2001** [koopa516/ParkourFortress-Bugs#43]
For example a Springboard on Pf_redux_b4 not launching you into the air, how they use to. 
This is the same for springboards on other maps as well.

How to reproduce:
Go up to a spring board (and example is show elbow in an image) and run towards the springboard, it use to fling you up into the air, now it does not. 

![image](https://user-images.githubusercontent.com/14146913/58748032-f991ea00-846a-11e9-9d5a-30663a9523a5.png)

**Comment by Jvp2001** [comment]
> For example a Springboard on Pf_redux_b4 not launching you into the air, how they use to.
> This is the same for springboards on other maps as well.
> 
> How to reproduce:
> Go up to a spring board, on PF_redux_b4 and run towards the springboard, it use to fling you up into the air, now it does not. The one on bf_callaghan_b3 (the last image) works fine.
> 
> ![image](https://user-images.githubusercontent.com/14146913/58748032-f991ea00-846a-11e9-9d5a-30663a9523a5.png)

![20190601130920_1](https://user-images.githubusercontent.com/14146913/58748372-a0788500-846f-11e9-8906-a1f9eb87880e.jpg)

**Comment by namishere** [comment]
This isn't a springboard, does not have a trigger_push.
