### ISSUE TITLE
Experimental Sliding Clearance

### ISSUE THREAD

**Issue by Magnanix** [koopa516/ParkourFortress-Bugs#48]
Can't remember if on SLAG, we could slide under the pair of bars in the bridge room (NOT THE ENDING HALLWAY)

However, with the new advanced sliding from experimental, clearance causes Temple to not be possible as the slide to dropdown for the zipline is inaccessible.

![20190606231847_1](https://user-images.githubusercontent.com/20764341/59079452-d70c3080-88b1-11e9-8b8e-5c628c7542af.jpg)
![20190606231855_1](https://user-images.githubusercontent.com/20764341/59079456-d8d5f400-88b1-11e9-952c-c630941add2a.jpg)

**Comment by namishere** [comment]
I can confirm the first, required one is fixed. Haven't tested the second. I'll investigate, but since this was a simple fix, I'm considering this closed.
