### ISSUE TITLE
You can glitch the camera into the floor on Eversion

### ISSUE THREAD

**Issue by KoziLord** [koopa516/ParkourFortress-Bugs#5]
You have to crouch walk into this raise on the spawn 
![image](https://user-images.githubusercontent.com/15251218/57410310-c3a27280-71ea-11e9-9087-a7419feecfb8.png)

Example: https://streamable.com/h86ir

**Comment by koopa516** [comment]
This is due to the timer zoning canceling any actions and will not be fixed. However, the zone will likely be adjusted.
