### ISSUE TITLE
[Eversion] barbed-wire damage bug

### ISSUE THREAD

**Issue by octoConnors** [koopa516/ParkourFortress-Bugs#6]
I landed on a barbed wire fence, immediately jumped off, and it didn't do enough damage to kill me. I had just over 30 health left. Afterwards, my health stopped regenerating.

**Comment by koopa516** [comment]
> I landed on a barbed wire fence, immediately jumped off, and it didn't do enough damage to kill me. I had just over 30 health left.
This is intended.
> Afterwards, my health stopped regenerating.
Fixed in commit c2ff0f.
