### ISSUE TITLE
State reset in Start Zone

### ISSUE THREAD

**Issue by Magnanix** [koopa516/ParkourFortress-Bugs#8]
Crouching at any point, from stand still or while moving, inside the Start Zone will cause a state reset. Looping between standing (or walking) to crouching (or sliding)

Can possible be tied with denial of parkour actions within the Start Zone to halt immediate advantages (TWRs)

**Comment by Magnanix** [comment]
When next to a crate or barrel, performing this will cause the camera to press into the ground and/or your player jumping on top of the object in front, without you touching jump.

Afterwards, if you continue this (it locks you moving in one direction, let go of forward to change direction) you can then proceed to force your camera under the player and intended position.

**Comment by namishere** [comment]
Fixed by adding a locked state on entering the start zone.
