### ISSUE TITLE
Grab detection

### ISSUE THREAD

**Issue by Magnanix** [koopa516/ParkourFortress-Bugs#9]
On pf_Mizuki, as of May 9th, the four grabs embedded into the pillar before the first pipe when traversing the default route, none can be grabbed currently.

On old PF, it was uncommon to grab the bottom three, and most common to grab the topmost.

**Comment by Magnanix** [comment]
Note, same pillar on pf_Mizuki, you can grab the corners.
It looks like the depth minimum is too far, striking the back wall.

This however causes conflicting instances when grabbing displacement walls.

**Comment by namishere** [comment]
Improved greatly by 43b5a0c.
